### ISSUE TITLE
Meguca archived

### ISSUE THREAD

**Issue by hawkoon** [Chiiruno/meguca#68]
Why did @bakape archive the meguca repo?

**Comment by rsdr** [comment]
No one really knows. The assumption is that the repository holder does not want to continue the project or that they no longer needed to. I would likely blame certain events of which I will not name that happened on Meguca.org
You could try reaching out to them, but I wouldn't expect a response.

**Comment by hawkoon** [comment]
> No one really knows. The assumption is that the repository holder does not want to continue the project or that they no longer needed to. I would likely blame certain events of which I will not name that happened on Meguca.org
> You could try reaching out to them, but I wouldn't expect a response.

Very sad, there aren't many IB softwares left. I hope someone will fork it and maintain it. Disappointing that he didn't at least explain why.

**Comment by rsdr** [comment]
> Very sad, there aren't many IB softwares left. I hope someone will fork it and maintain it. Disappointing that he didn't at least explain why.
I'll go a little further since I now know more. He didn't really use meguca upwards of recent, tied with some other personal issues it seems. Along with the website being taken down all culminated into that closing I suspect.

**Comment by Chiiruno** [comment]
This is the main fork now.
I'm not going to get into why he archived it.
