### ISSUE TITLE
Thumbnail included with uncontracted

### ISSUE THREAD

**Issue by Chiiruno** [Chiiruno/meguca#70]
![image](https://user-images.githubusercontent.com/30435868/68174207-dfd95f00-ff42-11e9-969b-1cab6af0cae2.png)

**Comment by Chiiruno** [comment]
@sora-chan

**Comment by sora-chan** [comment]
works for me

**Comment by sora-chan** [comment]
Oh I see the issue now. It only happens with webms or mp4s.
Setting line-height to 0px on `figure > a` element is another way to fix it without causing this issue.
PR soon
